linters.yml

diff --git a/.github/workflows/linters.yml b/.github/workflows/linters.yml
--- a/.github/workflows/linters.yml
+++ b/.github/workflows/linters.yml
@@ -15,9 +15,10 @@ jobs:
         with:
           node-version: "18.x"
       - name: Setup Lighthouse
-        run: npm install -g @lhci/cli@0.11.x
+        run: npm install -g @lhci/cli # Consider using the latest stable version
       - name: Lighthouse Report
         run: lhci autorun --upload.target=temporary-public-storage --collect.staticDistDir=.
+
   webhint:
     name: Webhint
     runs-on: ubuntu-22.04
@@ -27,11 +28,10 @@ jobs:
         with:
           node-version: "18.x"
       - name: Setup Webhint
-        run: |
-          npm install --save-dev hint@7.x
-          [ -f .hintrc ] || wget https://raw.githubusercontent.com/microverseinc/linters-config/master/html-css/.hintrc
+        run: npm install --save-dev hint # Consider using the latest stable version
       - name: Webhint Report
         run: npx hint .
+
   stylelint:
     name: Stylelint
     runs-on: ubuntu-22.04
@@ -41,11 +41,10 @@ jobs:
         with:
           node-version: "18.x"
       - name: Setup Stylelint
-        run: |
-          npm install --save-dev stylelint@13.x stylelint-scss@3.x stylelint-config-standard@21.x stylelint-csstree-validator@1.x
-          [ -f .stylelintrc.json ] || wget https://raw.githubusercontent.com/microverseinc/linters-config/master/html-css/.stylelintrc.json
+        run: npm install --save-dev stylelint stylelint-scss stylelint-config-standard stylelint-csstree-validator # Consider using the latest stable versions
       - name: Stylelint Report
         run: npx stylelint "**/*.{css,scss}"
+
   nodechecker:
     name: node_modules checker
     runs-on: ubuntu-22.04
@@ -53,4 +52,7 @@ jobs:
       - uses: actions/checkout@v3
       - name: Check node_modules existence
         run: |
-          if [ -d "node_modules/" ]; then echo -e "\e[1;31mThe node_modules/ folder was pushed to the repo. Please remove it from the GitHub repository and try again."; echo -e "\e[1;32mYou can set up a .gitignore file with this folder included on it to prevent this from happening in the future." && exit 1; fi
+          if [ -d "node_modules/" ]; then
+            echo -e "\e[1;31mError: The node_modules/ folder was pushed to the repo. Please remove it and ensure it's in your .gitignore file.\e[0m"
+            exit 1
+          fi
